<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract/Product.proto

namespace Ferror\GRPC\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>package.Nothing</code>
 */
class Nothing extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Ferror\GRPC\ProductMetadata\Product::initOnce();
        parent::__construct($data);
    }

}

