<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: contract/Product.proto

namespace Ferror\GRPC\Product;

use Spiral\GRPC;

interface ProductServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "package.ProductService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Nothing $in
    * @return Product
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function create(GRPC\ContextInterface $ctx, Nothing $in): Product;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Nothing $in
    * @return ProductCollection
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function getAll(GRPC\ContextInterface $ctx, Nothing $in): ProductCollection;
}
