<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: proto/Product.proto

namespace Ferror\GRPC\Product;

use Spiral\GRPC;

interface ProductServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "package.ProductService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Product $in
    * @return Product
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Create(GRPC\ContextInterface $ctx, Product $in): Product;
}
