<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract/Product.proto

namespace Ferror\GRPC\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>package.ProductCollection</code>
 */
class ProductCollection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .package.Product product = 1;</code>
     */
    private $product;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ferror\GRPC\Product\Product[]|\Google\Protobuf\Internal\RepeatedField $product
     * }
     */
    public function __construct($data = NULL) {
        \Ferror\GRPC\ProductMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .package.Product product = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Generated from protobuf field <code>repeated .package.Product product = 1;</code>
     * @param \Ferror\GRPC\Product\Product[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProduct($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ferror\GRPC\Product\Product::class);
        $this->product = $arr;

        return $this;
    }

}

