grpc:
    listen: "tcp://:50051"
    proto: "service.proto"
    workers:
        command: "php worker.php"
        pool:
            numWorkers: 4
limit:
    interval: 1
    services:
        grpc:
            maxMemory: 100
            TTL: 0
            idleTTL: 0
            execTTL: 60
