<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract/Product.proto

namespace Ferror\GRPC\ProductMetadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad6020a16636f6e74726163742f50726f647563742e70726f746f120770" .
            "61636b61676522090a074e6f7468696e67223a0a0750726f647563741212" .
            "0a0a6964656e746966696572180120012809120c0a046e616d6518022001" .
            "2809120d0a05707269636518032001280922360a1150726f64756374436f" .
            "6c6c656374696f6e12210a0770726f6475637418012003280b32102e7061" .
            "636b6167652e50726f6475637432760a0e50726f64756374536572766963" .
            "65122c0a0663726561746512102e7061636b6167652e4e6f7468696e671a" .
            "102e7061636b6167652e50726f6475637412360a06676574416c6c12102e" .
            "7061636b6167652e4e6f7468696e671a1a2e7061636b6167652e50726f64" .
            "756374436f6c6c656374696f6e4234ca0213466572726f725c475250435c" .
            "50726f64756374e2021b466572726f725c475250435c50726f647563744d" .
            "65746164617461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

