<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Product.proto

namespace Ferror\GRPC\ProductMetadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8010a1370726f746f2f50726f647563742e70726f746f12077061636b" .
            "616765223a0a0750726f6475637412120a0a6964656e7469666965721801" .
            "20012809120c0a046e616d65180220012809120d0a057072696365180320" .
            "012809323e0a0e50726f6475637453657276696365122c0a064372656174" .
            "6512102e7061636b6167652e50726f647563741a102e7061636b6167652e" .
            "50726f647563744234ca0213466572726f725c475250435c50726f647563" .
            "74e2021b466572726f725c475250435c50726f647563744d657461646174" .
            "61620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

